from .molecular_scale import *
from .afo import *
from .relation import *
from .organization import *
from .aft import *
from .skos import *
from .bfo_2_0 import *
from .portion_of_material import *
from .curation import *
from .system import *